name: Build and Deploy
on:
    push:
        branches:
            - master
jobs:
    build-and-deploy:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Install, lint, test and build
              run: |
                  npm ci --no-fund --no-optional
                  npm run lint
                  npm run test
                  npm run build

            # @see https://github.com/marketplace/actions/deploy-to-github-pages
            # @see https://docs.github.com/en/pages
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.1
              with:
                  branch: release
                  folder: dist