name: Build and Deploy
on:
    push:
        branches:
            - master
jobs:
    build-and-deploy:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            # An .env file has to be created on-the-fly as it's not in VCS
            # We also have to specify the BASE_URL variable so that the scr attribute of the generated script tags
            # will point to the right location
            - name: Install, lint, test and build
              run: |
                  echo "${{secrets.ENV}}" > .env
                  export BASE_URL="${{secrets.BASE_URL}}"
                  npm ci --no-fund --no-optional
                  npm run lint
                  npm run build
              # npm run test

            # @see https://github.com/JamesIves/github-pages-deploy-action
            # @see https://docs.github.com/en/pages
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.1
              with:
                  branch: release
                  folder: dist
